# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='gps',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='nfc',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='qrcode',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='course',
            name='latittude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='nfc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='qrcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
