# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_course_qrimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='qrtime',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
